import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils"
import Sidebar from '@/components/Sidebar';

import { Inter, IBM_Plex_Serif } from "next/font/google";
const inter = Inter({ subsets: ["latin"], variable: '--font-inter' });
const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-ibm-plex-serif'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
		<body className={`${inter.variable} ${ibmPlexSerif.variable}`}>
			{children}
		</body>
    </html>
  );
}
